baseURL: https://www.pcbaecker.com
languageCode: en-us
title: Philipp C. Baecker
theme: PaperMod
googleAnalytics: G-8W3M9LJNRE
homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...
socialIcons: # optional
  - name: linkedin
    url: https://www.linkedin.com/in/philipp-carl-b-a2a289221/
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Impress
                  url: impress/
                  weight: 10
                - name: Search
                  url: search/
                  weight: 10
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Dummy Description"
    author: Philipp C. Baecker
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]
    homeInfoParams:
        Title: "My personal blog"
        Content: >
            Welcome to my blog about things that helped me while my work as a software developer or personal projects.
            It often takes a lot of time to find solutions for problems that are easy to solve when you know the answer.
            As a result, I want to archive such solutions in this blog for myself and share them with the world in the hope the knowledge helps anyone.
    socialIcons:
        - name: github
          url: "https://github.com/pcbaecker"
    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true